lufor_shop/urls.py
from django.urls import path, include
"""
URL configuration for lufor_shop project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('authentication.urls'))
]

main/urls.py
from django.urls import include, path
from main.views import create_shop_flutter, show_main
from main.views import show_main, create_shop_entry
from main.views import show_main, create_shop_entry, show_xml
from main.views import show_main, create_shop_entry, show_xml, show_json
from main.views import show_main, create_shop_entry, show_xml, show_json, show_xml_by_id, show_json_by_id
from main.views import register
from main.views import login_user
from main.views import logout_user
from main.views import edit_shop, delete_shop, add_shop_entry_ajax, create_shop_flutter
app_name = 'main'
 
urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-shop-entry', create_shop_entry, name='create_shop_entry'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-shop/<uuid:id>', edit_shop, name='edit_shop'),
    path('delete/<uuid:id>', delete_shop, name='delete_shop'),
    path('create-shop-entry-ajax', add_shop_entry_ajax, name='add_shop_entry_ajax'),
    path('create-flutter/', create_shop_flutter, name='create_shop_flutter'),
    path('auth/', include('authentication.urls')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block meta %} {% endblock meta %}
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="{% static 'css/global.css' %}"/>
  </head>
  <body>
    {% block content %} {% endblock content %}
  </body>
</html>

templates/navbar.html
{% load static %}
<nav class="bg-white shadow-md fixed top-0 left-0 z-40 w-screen">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex items-center justify-between h-16">
        <div class="flex items-center">
          <h1 class="text-2xl font-semibold text-center text-gray-900">Luforshop</h1>
        </div>
        <div class="hidden md:flex justify-center items-center space-x-6">
            <a href="#" class="snav text-gray-700 font-medium px-4 py-2 rounded-3xl hover:bg-black hover:text-white transition duration-300 ease-in-out">Home</a>
            <a href="#" class="snav text-gray-700 font-medium px-4 py-2 rounded-3xl hover:bg-black hover:text-white transition duration-300 ease-in-out">Product</a>
            <a href="#" class="snav text-gray-700 font-medium px-4 py-2 rounded-3xl hover:bg-black hover:text-white transition duration-300 ease-in-out">Categories</a>
            <a href="#" class="snav text-gray-700 font-medium px-4 py-2 rounded-3xl hover:bg-black hover:text-white transition duration-300 ease-in-out">Promo</a>
            <a href="#" class="snav text-gray-700 font-medium px-4 py-2 rounded-3xl hover:bg-black hover:text-white transition duration-300 ease-in-out">Cart</a>
          </div>          
        <div class="hidden md:flex items-center">
          {% if user.is_authenticated %}
            <span class="text-gray-500 mr-6">Welcome, {{ user.username }}</span>
            <a href="{% url 'main:logout' %}" class="text-center bg-blue-600 hover:bg-blue-700 text-white font-medium py-2 px-4 rounded-full transition duration-300 ease-in-out">
              Logout
            </a>
          {% else %}
            <a href="{% url 'main:login' %}" class="text-center bg-blue-600 hover:bg-blue-700 text-gray-900 font-medium py-2 px-4 rounded-lg transition duration-300 ease-in-out mr-2">
              Login
            </a>
            <a href="{% url 'main:register' %}" class="text-center bg-blue-600 hover:bg-blue-700 text-white font-medium py-2 px-4 rounded-lg transition duration-300 ease-in-out">
              Register
            </a>
          {% endif %}
        </div>
        <div class="md:hidden flex items-center">
          <button class="mobile-menu-button">
            <svg class="w-6 h-6 text-gray-900" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor">
              <path d="M4 6h16M4 12h16M4 18h16"></path>
            </svg>
          </button>
        </div>
      </div>
    </div>
    <!-- Mobile menu -->
    <div class="mobile-menu hidden md:hidden px-4 w-full md:max-w-full">
      <div class="pt-2 pb-3 space-y-1 mx-auto">
        <a href="#" class="block snav text-left text-black px-3 py-2 rounded transition duration-300">Home</a>
        <a href="#" class="block snav text-left text-black px-3 py-2 rounded transition duration-300">Product</a>
        <a href="#" class="block snav text-left text-black px-3 py-2 rounded transition duration-300">Categories</a>
        <a href="#" class="block snav text-left text-black px-3 py-2 rounded transition duration-300">Promo</a>
        <a href="#" class="block snav text-left text-black px-3 py-2 rounded transition duration-300">Cart</a>
        {% if user.is_authenticated %}
          <span class="block text-gray-500 px-3 py-2">Welcome, {{ user.username }}</span>
          <a href="{% url 'main:logout' %}" class="block text-center bg-blue-600 hover:bg-blue-700 text-white font-medium py-2 px-4 rounded-lg transition duration-300 ease-in-out">
            Logout
          </a>
        {% else %}
          <a href="{% url 'main:login' %}" class="block text-center bg-blue-600 hover:bg-blue-700 text-gray-900 font-medium py-2 px-4 rounded-lg transition duration-300 ease-in-out mb-2">
            Login
          </a>
          <a href="{% url 'main:register' %}" class="block text-center bg-blue-600 hover:bg-blue-700 text-white font-medium py-2 px-4 rounded-lg transition duration-300 ease-in-out">
            Register
          </a>
        {% endif %}
      </div>
    </div>
    <script>
      const btn = document.querySelector("button.mobile-menu-button");
      const menu = document.querySelector(".mobile-menu");
    
      btn.addEventListener("click", () => {
        menu.classList.toggle("hidden");
      });
    </script>
  </nav>
  